# Generated by Django 3.0.7 on 2020-08-20 10:51

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseM',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=60)),
                ('buyer', models.CharField(max_length=12)),
                ('supplier', models.CharField(max_length=60)),
                ('call', models.CharField(max_length=20)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('number', models.FloatField()),
                ('unit', models.CharField(max_length=6)),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('Mid', models.ForeignKey(on_delete=django.db.models.expressions.Case, to='first.PurchaseM')),
            ],
        ),
    ]
